name: Run Unit Test
on:
  push:
    branches:
      - master
jobs:
  unit_test:
    name: Execute Unit Tests
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Maven unit tests
        run: mvn test